### ISSUE TITLE
Readme has incorrect examples

### ISSUE THREAD

**Issue by JuhQ** [mikeerickson/gulp-phplint#16]
`phpunit` mentioned twice even though it should be `phplint`

**Comment by mikeerickson** [comment]
@juhq thanks for report, I will fix it.  A product of muscle memory as I write phpunit so frequently 😜

**Comment by mikeerickson** [comment]
Fixed in [v0.3.3](https://github.com/mikeerickson/gulp-phplint/tree/v0.3.3)
