### ISSUE TITLE
Custom reporters can't catch stdout errors

### ISSUE THREAD

**Issue by kmck** [mikeerickson/gulp-phplint#3]
Hi there! Thanks for making this plugin. I was playing around with it and noticed that stdout errors (eg. `parse error`) don't make it through to custom reporters.

In particular, [this regex](https://github.com/mikeerickson/gulp-phplint/blob/master/index.js#L78) should probably fall back to `stdout` when `stderr` is empty (the built-in line-by-line logging is already doing this) as well as be loosened to allow an arbitrary amount of whitespace instead of exactly two spaces. after the colon.

Not sure how actively you're developing this, but I can make a PR if you want.

**Comment by mikeerickson** [comment]
@kmck It is updated regularly when issues arise or new features added to PHPUnit.   Should you wish to PR, by all means :-)  If not, I will review further over the weekend.

**Comment by mikeerickson** [comment]
@kmck My apologies for incorrectly mentioning PHPUnit, meant PHPLint.   Our gulp-phpunit plugin gets a lot more action so I guess it is muscle memory :-)

**Comment by kmck** [comment]
Thanks for merging my fix! Could you bump the version on npm?

**Comment by mikeerickson** [comment]
I will be bumping version later today

**Comment by mikeerickson** [comment]
@kmck Version 0.2.0 has been posted and published
