### ISSUE TITLE
Replace gulp-messenger because of logs dir creation

### ISSUE THREAD

**Issue by DanielSchwiperich** [mikeerickson/gulp-phplint#41]
gulp-messenger is always creating a `logs` dir at the project root which is pretty annoying. 
The recommended replacement for [gutil.log](https://github.com/gulpjs/gulp-util) is [fancy-log](https://github.com/js-cli/fancy-log)

logs dir creation: https://github.com/mikeerickson/gulp-messenger/blob/master/index.js#L263
caused by call https://github.com/mikeerickson/gulp-phplint/blob/master/index.js#L15

I see no option to avoid this creation with gulp-messenger.

**Comment by mikeerickson** [comment]
The better fix, will be to fix `gulp-messenger` to skip log directory creation if the `logToFile` property is `false` in the `msg.init...` call (which I will address as I would prefer to keep gulp-messenger included)

**Comment by DanielSchwiperich** [comment]
You are right. My first intention was to create an issue there and asking for exactly what you recommend. But since this would mean some kind of BC break I thought it's better placed here. 
I totally missed to see that gulp-messenger is also one of your packages 😄

**Comment by mikeerickson** [comment]
No worries, I will patch gulp-messenger this weekend
