### ISSUE TITLE
Module "exit-code" should be in dependencies, not a devDependencies

### ISSUE THREAD

**Issue by kmck** [mikeerickson/gulp-phplint#5]
In a clean install into an npm project, `reporters/fail.js` breaks because `exit-code` is required, but not a proper dependency of the project. (Installing `exit-code` alongside is a workaround.)

**Comment by mikeerickson** [comment]
Ya, I saw that same thing today when I was preparing the new build (but I thought I included exit-code in the package.json)?   I will update the dependency list accordingly right now.

**Comment by mikeerickson** [comment]
Fixed in 0.3.0

` $ npm i -S gulp-phplint@0.3.0` 

or

` $ npm i -S gulp-phplint@latest`
